slogan: “为世界上所有的美好而战”
email: wiseoaxyq@163.com
logo: "/images/logo.svg"

mathjax: false # 加载 LateX 数学公式库

favicon: # 配置网页图标
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # 开启“子页”功能，详见 README
  enable: true
  pages:
    - name: note # 文章的分类（category）名，如 developer
      path: # 若不设置则默认使用 name
      title: 开发者 # 菜单名，如 开发者
      icon: /images/icon/icon-code.svg # 图标的路径
      description: # 描述
    - name: DIY # 文章的分类（category）名，如 developer
      path: # 若不设置则默认使用 name
      title: 兴趣使然 # 菜单名，如 开发者
      icon: /images/icon/icon-pi.svg # 图标的路径
      description: # 描述

index: # 配置首页个性化内容
  motto: "但行好事 莫问前程"
  poem:
    - 酒入豪肠,七分酿成了月光
    - 余下的三分啸成剑气  绣口一吐就半个盛唐
  photo: /images/about.jpg
  about:
    title: 我
    text:
      - 锋芒毕露后，终归平淡时
      -
      - 八十亿中的小透明
      -
      - 但行好事 不忘初心

foot:
  title:
    - "愿时光永驻"
    - "愿星辰永熠"

# links: # 朋友
#   - name: "Theme Tranquility"
#     url: https://github.com/hooozen/hexo-theme-tranquility

social: # 账号
  - name: "github"
    icon: "/images/logo-github.svg"
    url: https://github.com/wiseoaxyq/
  - name: "友链-微信公众号"
    icon: "/images/logo-wx.svg"
    url: https://mp.weixin.qq.com/s/pgEVjoSVOyBi2xhCUna6HQ
  # - name: "知乎"
  #   icon: "/images/logo-zh.svg"
  #   url: https://www.zhihu.com/

reward: # 赞赏
  enable: false
  face: # 头像图片
  paycode: # 支付码图片
  text: “请作者喝杯咖啡”
  btnText: 喜欢作者

# see https://github.com/gitalk/gitalk
gitalk: # gitalk 评论
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: false
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>
